alter index IDX_DB_GROWTH_IDXS REBUILD COMPRESS ADVANCED LOW;
alter index IDX_DB_GROWTH_LOBS REBUILD COMPRESS ADVANCED LOW;
alter index IDX_DB_GROWTH_SEGS REBUILD COMPRESS ADVANCED LOW;
alter index IDX_DB_GROWTH_SIZES_PROJ REBUILD COMPRESS ADVANCED LOW;
alter index IDX_DB_GROWTH_TABS REBUILD COMPRESS ADVANCED LOW;